version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: exam_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: exam_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - exam_net

  redis:
    image: redis:7
    container_name: exam_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - exam_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: exam_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - exam_net

networks:
  exam_net:
    driver: bridge
